	
Function Happy_Birthday
{

    #Author: Trevor Sullivan (@pcgeek86)
    #Date: 2013-10-10
    #Description: Happy Birthday song, converted from Unicode to Base64 encoding, written with @RodTrent in mind.
    #Update: The Base64 encoded version was just for portability.
    #It's easy to decode Base64, but eiterh way, I included the original code below.
     
    
    #powershell.exe -encodedCommand JABCAGUAZQBwAEwAaQBzAHQAIAA9ACAAQAAoACAAIAAgACAAIABAAHsAIABQAGkAdABjAGgAIAA9ACAAMQAwADAAMAA7ACAATABlAG4AZwB0AGgAIAA9ACAAMwAwADAAOwAgAH0AOwAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEAMAAwADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADIAMAAwADsAIAB9ADsAIAAgACAAIAAgAEAAewAgAFAAaQB0AGMAaAAgAD0AIAAxADEANQAwADsAIABMAGUAbgBnAHQAaAAgAD0AIAA1ADAAMAA7ACAAfQA7ACAAIAAgACAAIABAAHsAIABQAGkAdABjAGgAIAA9ACAAMQAwADAAMAA7ACAATABlAG4AZwB0AGgAIAA9ACAANQAwADAAOwAgAH0AOwAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEAMwA1ADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADUAMAAwADsAIAB9ADsAIAAgACAAIAAgAEAAewAgAFAAaQB0AGMAaAAgAD0AIAAxADIANQAwADsAIABMAGUAbgBnAHQAaAAgAD0AIAA4ADAAMAA7ACAAfQA7ACAAIAAgACAAIAAgAEAAewAgAFAAaQB0AGMAaAAgAD0AIAAxADAAMAAwADsAIABMAGUAbgBnAHQAaAAgAD0AIAAzADAAMAA7ACAAfQA7ACAAIAAgACAAIABAAHsAIABQAGkAdABjAGgAIAA9ACAAMQAwADAAMAA7ACAATABlAG4AZwB0AGgAIAA9ACAAMgAwADAAOwAgAH0AOwAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEAMQA1ADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADUAMAAwADsAIAB9ADsAIAAgACAAIAAgAEAAewAgAFAAaQB0AGMAaAAgAD0AIAAxADAAMAAwADsAIABMAGUAbgBnAHQAaAAgAD0AIAA1ADAAMAA7ACAAfQA7ACAAIAAgACAAIABAAHsAIABQAGkAdABjAGgAIAA9ACAAMQA1ADAAMAA7ACAATABlAG4AZwB0AGgAIAA9ACAANQAwADAAOwAgAH0AOwAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEAMwA1ADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADgAMAAwADsAIAB9ADsAIAAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEAMAAwADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADMAMAAwADsAIAB9ADsAIAAgACAAIAAgAEAAewAgAFAAaQB0AGMAaAAgAD0AIAAxADAAMAAwADsAIABMAGUAbgBnAHQAaAAgAD0AIAAyADAAMAA7ACAAfQA7ACAAIAAgACAAIABAAHsAIABQAGkAdABjAGgAIAA9ACAAMgAwADAAMAA7ACAATABlAG4AZwB0AGgAIAA9ACAANQAwADAAOwAgAH0AOwAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEANwAwADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADUAMAAwADsAIAB9ADsAIAAgACAAIAAgAEAAewAgAFAAaQB0AGMAaAAgAD0AIAAxADMANwAwADsAIABMAGUAbgBnAHQAaAAgAD0AIAA1ADAAMAA7ACAAfQA7ACAAIAAgACAAIABAAHsAIABQAGkAdABjAGgAIAA9ACAAMQAyADIANQA7ACAATABlAG4AZwB0AGgAIAA9ACAANQAwADAAOwAgAH0AOwAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEAMQA1ADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADUAMAAwADsAIAB9ADsAIAAgACAAIAAgAEAAewAgAFAAaQB0AGMAaAAgAD0AIAAxADgAMAAwADsAIABMAGUAbgBnAHQAaAAgAD0AIAAzADAAMAA7ACAAfQA7ACAAIAAgACAAIABAAHsAIABQAGkAdABjAGgAIAA9ACAAMQA4ADAAMAA7ACAATABlAG4AZwB0AGgAIAA9ACAAMgAwADAAOwAgAH0AOwAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEANwAwADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADUAMAAwADsAIAB9ADsAIAAgACAAIAAgAEAAewAgAFAAaQB0AGMAaAAgAD0AIAAxADMANwAwADsAIABMAGUAbgBnAHQAaAAgAD0AIAA3ADAAMAA7ACAAfQA7ACAAIAAgACAAIABAAHsAIABQAGkAdABjAGgAIAA9ACAAMQA1ADAAMAA7ACAATABlAG4AZwB0AGgAIAA9ACAANQAwADAAOwAgAH0AOwAgACAAIAAgACAAQAB7ACAAUABpAHQAYwBoACAAPQAgADEAMwA3ADAAOwAgAEwAZQBuAGcAdABoACAAPQAgADUAMAAwADsAIAB9ADsAIAAgACAAIAAgACkAOwAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABCAGUAZQBwACAAaQBuACAAJABCAGUAZQBwAEwAaQBzAHQAKQAgAHsAIAAgACAAIAAgAFsAUwB5AHMAdABlAG0ALgBDAG8AbgBzAG8AbABlAF0AOgA6AEIAZQBlAHAAKAAkAEIAZQBlAHAAWwAnAFAAaQB0AGMAaAAnAF0ALAAgACQAQgBlAGUAcABbACcATABlAG4AZwB0AGgAJwBdACkAOwAgAH0A;
     
    $BeepList = @(
        @{ Pitch = 1000; Length = 300; };
        @{ Pitch = 1000; Length = 200; };
        @{ Pitch = 1150; Length = 500; };
        @{ Pitch = 1000; Length = 500; };
        @{ Pitch = 1350; Length = 500; };
        @{ Pitch = 1250; Length = 800; };
     
        @{ Pitch = 1000; Length = 300; };
        @{ Pitch = 1000; Length = 200; };
        @{ Pitch = 1150; Length = 500; };
        @{ Pitch = 1000; Length = 500; };
        @{ Pitch = 1500; Length = 500; };
        @{ Pitch = 1350; Length = 800; };
     
        @{ Pitch = 1000; Length = 300; };
        @{ Pitch = 1000; Length = 200; };
        @{ Pitch = 2000; Length = 500; };
        @{ Pitch = 1700; Length = 500; };
        @{ Pitch = 1370; Length = 500; };  # Doesn't sound quite right
        @{ Pitch = 1225; Length = 500; };  # Doesn't sound quite right
        @{ Pitch = 1150; Length = 500; };  # Doesn't sound quite right
        @{ Pitch = 1800; Length = 300; };
        @{ Pitch = 1800; Length = 200; };
        @{ Pitch = 1700; Length = 500; };
        @{ Pitch = 1370; Length = 700; };
        @{ Pitch = 1500; Length = 500; };
        @{ Pitch = 1370; Length = 500; };
        );
     
    foreach ($Beep in $BeepList) {
        [System.Console]::Beep($Beep['Pitch'], $Beep['Length']);
    }

}


